import { uid, type Project, type Scene, type SceneNode } from "./types";

export const createNode = (
  type: SceneNode["type"],
  duration: number,
  overrides: Partial<SceneNode> = {},
): SceneNode => ({
  id: uid(),
  type,
  name:
    type === "text"
      ? "文字"
      : type === "image"
        ? "图片"
        : type === "chart"
          ? "图表"
          : "图形",
  x: 120,
  y: 140,
  width: 520,
  height: 140,
  rotation: 0,
  opacity: 1,
  color: "#ffffff",
  text: type === "text" ? "在这里写下标题" : undefined,
  fontSize: 64,
  fontWeight: 600,
  data: type === "chart" ? [32, 54, 78, 92] : undefined,
  labels: ["春", "夏", "秋", "冬"],
  start: 0,
  end: duration,
  animation: "fade",
  locked: false,
  hidden: false,
  ...overrides,
});

export const blankScene = (): Scene => ({
  id: uid(),
  name: "新的镜头",
  duration: 180,
  background: "#173c35",
  notes: "",
  nodes: [],
});

export const createProject = (
  name: string,
  width: number,
  height: number,
): Project => ({
  id: uid(),
  name,
  width,
  height,
  fps: 30,
  revision: 0,
  updatedAt: new Date().toISOString(),
  scenes: [blankScene()],
  audio: [],
});

export function demoProject(): Project {
  const duration = 180;
  const image = "/media/landscape.jpg";
  const scenes: Scene[] = [
    {
      id: uid(),
      name: "走进山野",
      duration,
      background: "#173c35",
      notes: "远山与日落，开启一段山野之旅。",
      nodes: [
        createNode("image", duration, {
          name: "山野日落",
          x: 0,
          y: 0,
          width: 1280,
          height: 720,
          src: image,
          animation: "none",
        }),
        createNode("rect", duration, {
          name: "画面遮罩",
          x: 0,
          y: 0,
          width: 1280,
          height: 720,
          color: "#081f19",
          opacity: 0.38,
          animation: "none",
        }),
        createNode("text", duration, {
          name: "栏目名称",
          x: 80,
          y: 68,
          width: 500,
          height: 46,
          text: "山野之间  /  自然生活志",
          fontSize: 24,
          fontWeight: 500,
        }),
        createNode("text", duration, {
          name: "开场标题",
          x: 80,
          y: 230,
          width: 880,
          height: 220,
          text: "慢下来，\n走进山野。",
          fontSize: 84,
          fontWeight: 600,
          animation: "slide",
        }),
        createNode("text", duration, {
          name: "副标题",
          x: 85,
          y: 520,
          width: 840,
          height: 54,
          text: "让每一次出发，都回到生活本来的模样。",
          fontSize: 26,
        }),
        createNode("text", duration, {
          name: "镜头标记",
          x: 1110,
          y: 635,
          width: 90,
          height: 36,
          text: "01 / 04",
          fontSize: 20,
        }),
      ],
    },
    {
      id: uid(),
      name: "发现日常的美",
      duration,
      background: "#f4f5ef",
      notes: "自然的纹理和日常的细节。",
      nodes: [
        createNode("image", duration, {
          name: "日落风景",
          x: 64,
          y: 64,
          width: 550,
          height: 592,
          src: image,
          animation: "zoom",
        }),
        createNode("text", duration, {
          name: "章节",
          x: 680,
          y: 130,
          width: 430,
          height: 45,
          text: "自然，就是答案",
          fontSize: 22,
          color: "#507b65",
        }),
        createNode("text", duration, {
          name: "镜头标题",
          x: 680,
          y: 230,
          width: 510,
          height: 210,
          text: "把日常，\n过成风景。",
          fontSize: 66,
          color: "#203d31",
          animation: "slide",
        }),
        createNode("text", duration, {
          name: "镜头正文",
          x: 685,
          y: 505,
          width: 470,
          height: 100,
          text: "不必走得很远。\n一片山野，就足以重新看见自己。",
          fontSize: 24,
          color: "#5d6960",
        }),
      ],
    },
    {
      id: uid(),
      name: "四季都有新的故事",
      duration,
      background: "#173c35",
      notes: "四季出行数据，用图表表现不同季节。",
      nodes: [
        createNode("text", duration, {
          name: "章节",
          x: 80,
          y: 70,
          width: 500,
          height: 45,
          text: "每个季节，都是好时节",
          fontSize: 24,
          color: "#b5d8c4",
        }),
        createNode("text", duration, {
          name: "镜头标题",
          x: 80,
          y: 150,
          width: 1100,
          height: 100,
          text: "四季，都有新的故事。",
          fontSize: 62,
        }),
        createNode("chart", duration, {
          name: "四季出行趋势",
          x: 100,
          y: 320,
          width: 1000,
          height: 270,
          color: "#a4d9b7",
          data: [45, 75, 95, 62],
          animation: "fade",
        }),
        createNode("text", duration, {
          name: "数据说明",
          x: 80,
          y: 650,
          width: 700,
          height: 35,
          text: "示例数据 · 可在属性面板修改",
          fontSize: 18,
          color: "#b5d8c4",
        }),
      ],
    },
    {
      id: uid(),
      name: "下一站，山野之间",
      duration,
      background: "#eef2ed",
      notes: "品牌落版，邀请下一次出发。",
      nodes: [
        createNode("circle", duration, {
          name: "品牌图形",
          x: 550,
          y: 100,
          width: 180,
          height: 180,
          color: "#2a7355",
          animation: "zoom",
        }),
        createNode("text", duration, {
          name: "品牌标题",
          x: 250,
          y: 330,
          width: 780,
          height: 120,
          text: "下一站，山野之间。",
          fontSize: 64,
          color: "#193e2c",
        }),
        createNode("text", duration, {
          name: "结尾文案",
          x: 400,
          y: 510,
          width: 640,
          height: 70,
          text: "去自然里，找回自己的节奏。",
          fontSize: 28,
          color: "#597063",
        }),
      ],
    },
  ];
  return {
    id: uid(),
    name: "山野之间 · 品牌故事",
    width: 1280,
    height: 720,
    fps: 30,
    revision: 0,
    updatedAt: new Date().toISOString(),
    scenes,
    audio: [],
  };
}
